name: Publish

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test

  publish-npm:
    if: github.repository == 'dek577/homebridge-watchdog15' && github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        - uses: actions/checkout@v1
        - uses: actions/setup-node@v1
        with:
            node-version: 10
            registry-url: https://npm.pkg.github.com
        - run: npm ci
        - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            